### ISSUE TITLE
Extra length octet

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls-flags#10]
I seem to remember this being discussed, so close if I missed it.

The calculus for choosing to use this over an empty extension is pretty poor for early adopters.  The first user of this has to deal with paying 6 bytes for that privilege, whereas an empty extension only uses 4.  The overhead of 5 is shared between other users, but maybe it could be 4:

```
      struct {
         opaque flags[ceil((max(flag) + 1) / 8];
      } FlagExtensions;
```

Not sure about the math there.  Words would also work well enough.

**Comment by yoavnir** [comment]
The first user, the one who pays the 6 bytes already exists, so the marginal cost for the next seven extensions is zero.
This is, of course, depends on the adoption rate of cross-sni-resumption.  If nobody users that, then the cost for the second adopter is still 6 bytes (or a marginal cost of 2 bytes over using a special extension).
Do you think the document needs to reflect this discussion?

**Comment by chris-wood** [comment]
@martinthomson would you like to see further clarification here?

**Comment by martinthomson** [comment]
What I was looking for was the removal of the leading length byte.  Maybe I was too obtuse.

**Comment by ekr** [comment]
Oh, I don't think we probably should do that. I get that the byte is redundant, but that would break with basically every extension. Somewhat less interestingly, cTLS assumes extensions self-delimit

**Comment by martinthomson** [comment]
That seems like a flaw in cTLS.  Either way, I don't much care.  I just wanted to ask the question.  It seems like a high price to pay if the point of this is to save bytes.

Maybe the answer is that cTLS renders this extension obsolete at birth.

**Comment by ekr** [comment]
> That seems like a flaw in cTLS.

Well, it's what lets you save two bytes of length per extension.

**Comment by chris-wood** [comment]
Based on the WGLC(s) done so far, I'm closing this issue without a technical change. @yoavnir, please feel free to re-open if you'd like to address this with an editorial clarification of the implications for early adopters.
