### ISSUE TITLE
Usage also for (D)TLS 1.2

### ISSUE THREAD

**Issue by boaks** [tlswg/tls-flags#13]
Though the title implies for me, that only the usage with (D)TLS 1.3 is considered, I'm not sure about the intention according (DT)TLS 1.2?

[DTLS-RRC](https://github.com/tlswg/dtls-rrc/pull/4/files#r734932553) is considering to use this, with that, the answer to the support for DTLS 1.2 may get important.

**Comment by thomas-fossati** [comment]
> I encourage you and Thomas to raise this issue on the TLS mailing list.

Thanks @yoavnir -- Hannes brought the topic to the [list](https://mailarchive.ietf.org/arch/msg/tls/ryMkQS3ekPgu3D9Aa_e4nNnQTUY/) but there was no followup.

> Maybe also at the TLS meeting.

I don't see tlsflags on the (WIP) agenda for IETF 112.  Are you planning to present it there?

**Comment by chris-wood** [comment]
@yoavnir if you'd like some time to discuss tls-flags and the question of 1.2 support, please let me know!

**Comment by yoavnir** [comment]
> > Maybe also at the TLS meeting.
> 
> I don't see tlsflags on the (WIP) agenda for IETF 112. Are you planning to present it there?

Now I am. It's on the agenda

**Comment by chris-wood** [comment]
Per discussion in IETF 112, there did not seem to be consensus to back port this for 1.2. Closing.
