### ISSUE TITLE
Clarify flag acknowledgement expectations

### ISSUE THREAD

**Issue by chris-wood** [tlswg/tls-flags#19]
As discussed [on the list](https://mailarchive.ietf.org/arch/msg/tls/83opT1W6jjIbSYu9dH_5r35IIFg/). There does not appear to be clarity on this point, and (with no hat), I don't think _requiring_ acknowledgement should be required. That seems like behavior each flag should specify themselves.

**Comment by yoavnir** [comment]
My first instinct was to respond that of course, we require acknowledgment -- any extension would need it.  But then I read draft-kampanakis.  Now I see.

OK, I'll come up with a PR that updates the draft to not require it, although I still think that the extension in draft-kampanakis is an outlier, and that most extensions will require acknowledgment.

**Comment by yoavnir** [comment]
PR #20 proposed for this.

**Comment by seanturner** [comment]
@yoavnir I think you can close this one out.
