### ISSUE TITLE
"Recommended" Column

### ISSUE THREAD

**Issue by emanjon** [tlswg/tls-flags#32]
`Recommended, which is a Y/N value determined in the document defining the optional feature.
`

I assume this should follow the definition in Section 3 of draft-ietf-tls-rfc8447bis. Three suggestions:

- I think it should be Y/N/D
- A reference to RFC8447bis would maybe be good.
- I think it would be better to just remove "determined in the document defining the optional feature." as a later document might redefine the value.

**Comment by seanturner** [comment]
I think this is just a case of this I-D pre-dating -rfc8447bis.  It should be aligned when it gets revived/revised.
